awslabs/clickstream-android

- .github/ISSUE_TEMPLATE/1.bug_report.yaml
- .github/ISSUE_TEMPLATE/2.feature_report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
1. add bug_report and feature_report template for issue.
2. add pr template.
Close #6
> chore: add github templates for issue and pr

- README.md
1. change record event api use the `ClickstreamEvent`.
NA
> fix: update readme for ClickstreamEvent

- README.md
1. update readme for introduction
NA
> chore: update readme for introduction

- .github/workflows/publish.yml
1. add action for maven publish
test [action](https://github.com/awslabs/clickstream-android/actions/runs/5102599855) passed
> chore: add publish workflow to maven repo

- README.md
add troubleshooting in readme to resolve the kotlin version duplicate.
> chore: add troubleshooting in readme

- README.md
- clickstream/src/main/java/software/aws/solution/clickstream/AutoEventSubmitter.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/EventRecorder.java
- clickstream/src/test/java/software/aws/solution/clickstream/EventRecorderTest.java
- gradle.properties
1. delete log in timer.
2. update sdk version
> chore: simplify log

- clickstream/src/main/java/software/aws/solution/clickstream/client/AutoRecordEventClient.java
- clickstream/src/test/java/software/aws/solution/clickstream/AutoRecordEventClientTest.java
1. add flush events when app move to background.
add test case for assert the event executorService count is 1 when app move to background.
> feat: add flush events action when app move to background.

- README.md
- clickstream/src/main/java/software/aws/solution/clickstream/ClickstreamEvent.java
- clickstream/src/test/java/software/aws/solution/clickstream/IntegrationTest.java
- gradle.properties
1.  add long type for ClickstreamEvent
Add long type attribute to an event and record, then assert the long type event attribute from sqlite is equals to the record value.
> feat: add long type for ClickstreamEvent

- README.md
1. change isTrackAppExceptionEvents default value to true
> fix: update readme for isTrackAppExceptionEvents default value.

- README.md
1. add solution link in readme
> chore: add solution link in readme

- README.md
- clickstream/src/main/java/software/aws/solution/clickstream/AWSClickstreamPlugin.java
- clickstream/src/main/java/software/aws/solution/clickstream/ActivityLifecycleManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/ClickstreamAnalytics.java
- clickstream/src/test/java/software/aws/solution/clickstream/ActivityLifecycleManagerUnitTest.java
- gradle.properties
1. support application context when initialize SDK
1. use activity context to test bad case.
2. tested by NotePad App.
> feat: support application context when initialize SDK.

- clickstream/src/main/java/software/aws/solution/clickstream/client/AutoRecordEventClient.java
- clickstream/src/test/java/software/aws/solution/clickstream/AutoRecordEventClientTest.java
1. change the screen unique id generation method
> fix: change the screen unique id generation method

- build.gradle
- clickstream/src/main/java/software/aws/solution/clickstream/client/AnalyticsEvent.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/EventRecorder.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/network/NetRequest.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/util/JSONBuilder.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/util/StringUtil.java
- clickstream/src/test/java/software/aws/solution/clickstream/AnalyticsEventTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/EventRecorderTest.java
1. change hash code calculation method to sha256
2. delete hashCode form each event attribute
3. add hashCode into query parameter
> feat: add hash code to request query parameter

- README.md
- clickstream/src/main/java/software/aws/solution/clickstream/AWSClickstreamPlugin.java
- clickstream/src/main/java/software/aws/solution/clickstream/ActivityLifecycleManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/ClickstreamAnalytics.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/ClickstreamExceptionHandler.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/ClickstreamManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/util/ThreadUtil.java
- clickstream/src/test/java/software/aws/solution/clickstream/AutoRecordEventClientTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/ExceptionHandlerTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/InitClientTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/IntegrationTest.java
1. support enable and disable SDK.
Added test cases for timer, activity lifecycle, application lifecycle and exception handlers, which will be disabled when the SDK is disabled
> feat: support enable and disable SDK

- README.md
> feat: add custom item attribute in readme

- clickstream/src/main/java/software/aws/solution/clickstream/client/AnalyticsClient.java
- clickstream/src/test/java/software/aws/solution/clickstream/AnalyticsClientTest.java
1. change user attribute to JSONObject
> fix: change user attribute to JSONObject

- .github/workflows/integration_test.yml
> chore: fix pytest version in integration test

- .github/workflows/tag_and_release.yml
1. fix Github release version expression
tested by this [action](https://github.com/awslabs/clickstream-swift/actions/runs/7737807086/job/21097425164)
> fix: the expression of github release version

- README.md
- gradle.properties
1. release: clickstream Android 0.11.0
> release: clickstream Android 0.11.0

- clickstream/src/main/java/software/aws/solution/clickstream/ActivityLifecycleManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/ScreenRefererTool.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/util/PreferencesUtil.java
- clickstream/src/test/java/software/aws/solution/clickstream/AutoRecordEventClientTest.java
- integrationtest/devicefarm/logcat_test.py
1. add screen view event after session start
added the test case testSessionTimeoutAfterReopenTheApp
> feat: add screen view event after session start

- README.md
- gradle.properties
1. release: clickstream Android 0.11.1
> release: clickstream Android 0.11.1

- .github/workflows/tag_and_release.yml
1. make release tag name consistent with git tag
> fix: make release tag name consistent with git tag

- clickstream/src/main/java/software/aws/solution/clickstream/ActivityLifecycleManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/AutoRecordEventClient.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/ClickstreamManager.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/Session.java
- clickstream/src/main/java/software/aws/solution/clickstream/client/SessionClient.java
- clickstream/src/test/java/software/aws/solution/clickstream/ActivityLifecycleManagerUnitTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/AnalyticsClientTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/AutoRecordEventClientTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/EventRecorderTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/ExceptionHandlerTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/IntegrationTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/SessionClientTest.java
- clickstream/src/test/java/software/aws/solution/clickstream/db/DBUtilTest.java
1. support lazy initialization of the SDK and will also send _first_open, _app_start and _session_start events.
> feat: support lazy initialization of the SDK

- README.md
- gradle.properties
1. release: clickstream Android 0.12.0
> release: clickstream Android 0.12.0

- .github/workflows/code_coverage.yml
- .github/workflows/publish.yml
- publishing.gradle
*Issue #, if available:*
tested in local environment
> ci: support sonatype user token for publishing

- README.md
- gradle.properties
1. release: clickstream Android 0.13.0
> release: clickstream Android 0.13.0

- README.md
- gradle.properties
1. release: clickstream Android 0.14.0
> release: clickstream Android 0.14.0

- README.md
- gradle.properties
1. release: clickstream Android 0.14.1
> release: clickstream Android 0.14.1
